# markdown

In [2]:
import numpy as np
from sklearn.datasets import make_regression
 
# Create data set.
X = np.array([[1, 5, 3], [4, 77, 6], [7, 134, 9], [4, 4, 4]])
y = np.array([1, 2 ,3, 5])
X, y

(array([[  1,   5,   3],
        [  4,  77,   6],
        [  7, 134,   9],
        [  4,   4,   4]]),
 array([1, 2, 3, 5]))

In [3]:
def linear_regression_normal_equation(X, y):
    X_transpose = np.transpose(X)
    X_transpose_X = np.dot(X_transpose, X)
    X_transpose_y = np.dot(X_transpose, y)
    print(X_transpose_X)
    try:
        theta = np.linalg.solve(X_transpose_X, X_transpose_y)
        return theta
    except np.linalg.LinAlgError:
        return None
 
 
# Add a column of ones to X for the intercept term
print(X)
X_with_intercept = np.c_[np.ones((X.shape[0], 1)), X]
print(X_with_intercept)
 
theta = linear_regression_normal_equation(X_with_intercept, y)
if theta is not None:
    print(theta)
else:
    print("Unable to compute theta. The matrix X_transpose_X is singular.")

[[  1   5   3]
 [  4  77   6]
 [  7 134   9]
 [  4   4   4]]
[[  1.   1.   5.   3.]
 [  1.   4.  77.   6.]
 [  1.   7. 134.   9.]
 [  1.   4.   4.   4.]]
[[4.0000e+00 1.6000e+01 2.2000e+02 2.2000e+01]
 [1.6000e+01 8.2000e+01 1.2670e+03 1.0600e+02]
 [2.2000e+02 1.2670e+03 2.3926e+04 1.6990e+03]
 [2.2000e+01 1.0600e+02 1.6990e+03 1.4200e+02]]
[ 3.66666667e+00  1.83333333e+00 -2.12899118e-14 -1.50000000e+00]
