In [26]:
import numpy as np
import scipy.linalg

## State

In [17]:
state = {
    0 : "Burger",
    1 : "Pizza",
    2 : "Hotdog"
}
state

{0: 'Burger', 1: 'Pizza', 2: 'Hotdog'}

## State Transition Matrix

In [18]:
A = np.array([[0.2, 0.6, 0.2], [0.3, 0, 0.7], [0.5, 0, 0.5]])
A

array([[0.2, 0.6, 0.2],
       [0.3, 0. , 0.7],
       [0.5, 0. , 0.5]])

## Random Walk on the Makov Chain

In [19]:
n = 15
start_state = 2
print(state[start_state], "--->", end = " ")
prev_state = start_state

while n-1:
    curr_state = np.random.choice([0, 1, 2], p= A[prev_state])
    print(state[curr_state], "--->", end= " ")
    prev_state = curr_state
    n -= 1

print("\nprocess done")

Hotdog ---> Burger ---> Burger ---> Burger ---> Pizza ---> Burger ---> Pizza ---> Hotdog ---> Burger ---> Pizza ---> Hotdog ---> Burger ---> Pizza ---> Hotdog ---> Burger ---> 
process done


### Approach 1: Monte Carlo

In [25]:
steps = 10**6
start_state = 0
pi = np.array([0, 0, 0])
pi[start_state] = 1
prev_state = start_state

i = 0
while i < steps:
    curr_state = np.random.choice([0, 1, 2], p = A[prev_state])
    pi[curr_state] += 1
    prev_state = curr_state
    i += 1

print("pi = ", pi/steps)

pi =  [0.352087 0.211288 0.436626]


### Approach 2: Repeated Matrix Multiplication

In [24]:
steps = 10**3
A_n = A

i = 0
while i < steps:
    A_n = np.matmul(A_n, A)
    i += 1

print("A^n = \n", A_n, "\n")
print("pi = ", A_n[0])

A^n = 
 [[0.35211268 0.21126761 0.43661972]
 [0.35211268 0.21126761 0.43661972]
 [0.35211268 0.21126761 0.43661972]] 

pi =  [0.35211268 0.21126761 0.43661972]


### Approach 3: Finding Left EigenVectors

In [27]:
values, left = scipy.linalg.eig(A, right = False, left = True)

print("left eigen vectors = \n", left, "\n")
print("eigen values = \n", values)

left eigen vectors = 
 [[-0.58746336+0.j         -0.16984156-0.35355339j -0.16984156+0.35355339j]
 [-0.35247801+0.j          0.67936622+0.j          0.67936622-0.j        ]
 [-0.72845456+0.j         -0.50952467+0.35355339j -0.50952467-0.35355339j]] 

eigen values = 
 [ 1.  +0.j        -0.15+0.3122499j -0.15-0.3122499j]


In [28]:
pi = left[:, 0]
pi_normalized = [(x/np.sum(pi)).real for x in pi]
pi_normalized

[0.35211267605633795, 0.21126760563380292, 0.43661971830985913]